### PR TITLE
Improve requirements documentation

### PR DESCRIPTION
**Pull request by drhelius**

### CODE REVIEW

**Comment by frsl92** [comment]
@drhelius looks good. Shall we also rename the VISION_REGION to keep the same naming convention?

**Comment by drhelius** [comment]
> @drhelius looks good. Shall we also rename the VISION_REGION to keep the same naming convention?

I think so, but I'm looking for it and I can't see where it is used? Is this a variable we could remove?

**Comment by frsl92** [comment]
If we won't use it in the the Lab 7, let's remove it.

**Comment by drhelius** [comment]
@frsl92 just removed it. Let me know if it is ok and feel free to merge if ready.

**Pull request merged**
